fix

diff --git a/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl b/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl
--- a/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl
+++ b/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl
@@ -5,6 +5,14 @@ set -euo pipefail
 {{ template "aqua_install.sh" . }}
 
 log_info "CLI Tools | Performing aqua standard setup..."
+if [[ ! -e "$AQUA_GLOBAL_CONFIG" ]]; then
+  log_error "CLI Tools | Tags[${tags}] | Global aqua configuration does not exist, cannot proceed!"
+  exit 1
+fi
+if [[ -e "$AQUA_POLICY_CONFIG" ]]; then
+  log_info "CLI Tools | Tags[${tags}] | Allowing aqua policy file: $AQUA_POLICY_CONFIG..."
+  aqua policy allow $AQUA_POLICY_CONFIG
+fi
 aqua_install standard
 echo "-------------------------------------------------------------------------------------------"
 echo
