fix

diff --git a/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl b/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl
--- a/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl
+++ b/.chezmoiscripts/run_after_21_aqua_init.sh.tmpl
@@ -4,15 +4,16 @@ set -eo pipefail
 {{ template "script_header.sh" . }}
 {{ template "aqua_install.sh" . }}
 
-log_info "CLI Tools | Performing aqua standard setup..."
-if [[ ! -e "$AQUA_GLOBAL_CONFIG" ]]; then
-  log_error "CLI Tools | Tags[baseline] | Global aqua configuration does not exist, cannot proceed!"
+log_info "CLI Tools | Tags[baseline] | Initializing Aqua..."
+if ! command -v aqua > /dev/null; then
+  log_error "CLI Tools | Tags[baseline] | Aqua binary is not in path, cannot proceed!"
   exit 1
 fi
-if [[ ! -z "$AQUA_POLICY_CONFIG" && -e "$AQUA_POLICY_CONFIG" ]]; then
-  log_info "CLI Tools | Tags[baseline] | Allowing aqua policy file: $AQUA_POLICY_CONFIG..."
-  aqua policy allow $AQUA_POLICY_CONFIG
-fi
-aqua_install optional
+log_info "CLI Tools | Tags[baseline] | Installing or upgrading aqua packages..."
+aqua install --tags baseline 2>&1 | sed -E 's|^(.*)|  \1|g'
+log_success "CLI Tools | Tags[baseline] | Aqua install is complete."
+echo
+log_info "CLI Tools | Tags[baseline] | Display installed packages..."
+aqua list --installed --all | column -t 2>&1 | sed -E 's|^(.*)|  \1|g'  
 echo "-------------------------------------------------------------------------------------------"
 echo
diff --git a/.chezmoiscripts/run_before_21_aqua_prerequisites.sh.tmpl b/.chezmoiscripts/run_before_21_aqua_prerequisites.sh.tmpl
--- a/.chezmoiscripts/run_before_21_aqua_prerequisites.sh.tmpl
+++ b/.chezmoiscripts/run_before_21_aqua_prerequisites.sh.tmpl
@@ -4,9 +4,18 @@ set -euo pipefail
 {{ template "script_header.sh" . }}
 {{ template "aqua_install.sh" . }}
 
-log_info "CLI Tools | Performing aqua prerequisites setup..."
-
 cd {{ .chezmoi.sourceDir }}/dot_config/aquaproj-aqua
-aqua_install baseline,optional
+
+log_info "CLI Tools | Tags[prerequisites] | Initializing Aqua..."
+if ! command -v aqua > /dev/null; then
+  log_error "CLI Tools | Tags[prerequisites] | Aqua binary is not in path, cannot proceed!"
+  exit 1
+fi
+log_info "CLI Tools | Tags[prerequisites] | Installing or upgrading aqua packages..."
+aqua install --tags prerequisites 2>&1 | sed -E 's|^(.*)|  \1|g'
+log_success "CLI Tools | Tags[prerequisites] | Aqua install is complete."
+echo
+log_info "CLI Tools | Tags[prerequisites] | Display installed packages..."
+aqua list --installed --all | column -t 2>&1 | sed -E 's|^(.*)|  \1|g'  
 echo "-------------------------------------------------------------------------------------------"
 echo
